# Generated by Django 5.2.6 on 2025-09-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
